[package]
name = "rust-neuralnet"
version = "0.0.1"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]

[dependencies]
rand = "0.4.2"
ndarray = "0.11.0"

[dev-dependencies]
approx = "0.1.1"
